version: 1.0.0.{build}

build:
  verbosity: minimal
  project: EPiRestrictMultiple.sln

cache:
  - packages -> **\packages.config

before_build:
  - cmd: nuget sources add -Name EPiServer -Source http://nuget.episerver.com/feed/packages.svc/
  - cmd: nuget restore