
# version format
version: 1.0.{build}

cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

before_build:
  nuget sources add -Name EPiServer -Source http://nuget.episerver.com/feed/packages.svc/
  nuget restore